server:
  port : 5000
spring:
  jpa:
    database: MYSQL	#MYSQL사용
    show-sql: true	#JPA가 실행한 sql 쿼리를 로그로 출력할 지 여부
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}
    username: ${rds.username}
    password: ${rds.password}